In [3]:
from bs4 import BeautifulSoup as bs
import pandas as pd
import requests

In [5]:
#configurations 
headers = {
    'User-Agent': "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
    }

#Scrapping
url='https://www.riyasewana.com/search/motorcycles'
response = requests.request("GET", url, headers=headers)

# parse the downloaded data
data = bs(response.content, 'html.parser')
#cards=data.find_all('div',attrs={'id','wrapper'})
#print(len(cards))
cards=data.find_all('li',attrs={'class','item round'})

In [12]:
scraped_data=[]
img_url=[]

for card in cards[:15]:
    Bike_name_year=card.find('h2').text
    Bike_image=card.find('img')['src']
    Bike_city=card.find('div',attrs={'class','boxintxt'}).text[1::]
    Bike_price=card.find('div',attrs={'class','boxintxt b'}).text[5::]
    Date_posted=card.find('div',attrs={'class','boxintxt s'}).text[1::]
    if Bike_price!='tiable':
        Bike_price=int(Bike_price.replace(',',''))
    else:
        continue
    card_details={}
    card_details['Bike_name_year']=Bike_name_year
    card_details['Bike_image']=Bike_image
    card_details['Bike_price']=Bike_price
    card_details['Bike_city']=Bike_city
    card_details['Date_posted']=Date_posted
    response=requests.get('http:'+Bike_image)
    
    # Save the images into or folder
    
    with open(Bike_name_year+'.jpg', 'wb') as handle:
   
        for block in response.iter_content(1024):
            if not block:
                break

            handle.write(block)
    
    scraped_data.append(card_details)

In [14]:
bikes=pd.DataFrame.from_dict(scraped_data)
bikes.head(10)

,Bike_city,Bike_image,Bike_name_year,Bike_price,Date_posted
0,Kurunegala,//riyasewana.com/thumb/thumbhonda-cd-125-22257...,Honda Cd 125 Benly 1996 Motorbike,298000,2021-08-02
1,Minuwangoda,//riyasewana.com/thumb/thumbbajaj-ct100-222503...,Bajaj Ct100 2004 Motorbike,67000,2021-08-02
2,Kiribathgoda,//riyasewana.com/thumb/thumbbajaj-ct-100-22247...,Bajaj Ct-100 2013 Motorbike,155000,2021-08-02
3,Gampaha,//riyasewana.com/thumb/thumbbajaj-chetak-22246...,Bajaj Chetak 1996 Motorbike,120000,2021-08-02
4,Kandy,//riyasewana.com/thumb/thumbbajaj-ct-100-22243...,Bajaj Ct-100 2005 Motorbike,88000,2021-08-02
5,Matara,//riyasewana.com/thumb/thumbbajaj-xcd-22233271...,Bajaj Xcd 2010 Motorbike,87000,2021-08-02
6,Negombo,//riyasewana.com/thumb/thumbtvs-wego-222321413...,TVS Wego 2013 Motorbike,215000,2021-08-02
7,Kuliyapitiya,//riyasewana.com/thumb/thumbyamaha-fz-s-v2-222...,Yamaha Fz-s V2 2015 Motorbike,410000,2021-08-02
8,Jaffna,//riyasewana.com/thumb/thumbbajaj-ct-100-22231...,Bajaj Ct-100 2015 Motorbike,175000,2021-08-02
9,Matara,//riyasewana.com/thumb/thumbhero-honda-plsan-p...,Hero-Honda Plsan Por 2005 Motorbike,57000,2021-08-02